export const STATES = [
    { label: 'Alabama', value: 'AL' },
    { label: 'Alaska', value: 'AK' },
    { label: 'Arizona', value: 'AZ' },
    { label: 'Arkansas', value: 'AR' },
    { label: 'California', value: 'CA' },
    { label: 'Colorado', value: 'CO' },
    { label: 'Connecticut', value: 'CT' },
    { label: 'Delaware', value: 'DE' },
    { label: 'Florida', value: 'FL' },
    { label: 'Georgia', value: 'GA' },
    { label: 'Hawaii', value: 'HI' },
    { label: 'Idaho', value: 'ID' },
    { label: 'Illinois', value: 'IL' },
    { label: 'Indiana', value: 'IN' },
    { label: 'Iowa', value: 'IA' },
    { label: 'Kansas', value: 'KS' },
    { label: 'Kentucky', value: 'KY' },
    { label: 'Louisiana', value: 'LA' },
    { label: 'Maine', value: 'ME' },
    { label: 'Maryland', value: 'MD' },
    { label: 'Massachusetts', value: 'MA' },
    { label: 'Michigan', value: 'MI' },
    { label: 'Minnesota', value: 'MN' },
    { label: 'Mississippi', value: 'MS' },
    { label: 'Missouri', value: 'MO' },
    { label: 'Montana', value: 'MT' },
    { label: 'Nebraska', value: 'NE' },
    { label: 'Nevada', value: 'NV' },
    { label: 'New Hampshire', value: 'NH' },
    { label: 'New Jersey', value: 'NJ' },
    { label: 'New Mexico', value: 'NM' },
    { label: 'New York', value: 'NY' },
    { label: 'North Carolina', value: 'NC' },
    { label: 'North Dakota', value: 'ND' },
    { label: 'Ohio', value: 'OH' },
    { label: 'Oklahoma', value: 'OK' },
    { label: 'Oregon', value: 'OR' },
    { label: 'Pennsylvania', value: 'PA' },
    { label: 'Rhode Island', value: 'RI' },
    { label: 'South Carolina', value: 'SC' },
    { label: 'South Dakota', value: 'SD' },
    { label: 'Tennessee', value: 'TN' },
    { label: 'Texas', value: 'TX' },
    { label: 'Utah', value: 'UT' },
    { label: 'Vermont', value: 'VT' },
    { label: 'Virginia', value: 'VA' },
    { label: 'Washington', value: 'WA' },
    { label: 'West Virginia', value: 'WV' },
    { label: 'Wisconsin', value: 'WI' },
    { label: 'Wyoming', value: 'WY' },
]

export const BOOK_CONDITION = [
    { label: 'New', value: 'New' },
    { label: 'Like New', value: 'LikeNew' },
    { label: 'Used', value: 'Used' },
    { label: 'Ripped', value: 'Ripped' },
  ];

export const COUNTRY = [
    { label: 'USA', value: 'USA' },
    { label: 'Canada', value: 'CA' },
    { label: 'India', value: 'IN' },
  ];

  export const BOOKGENRE = [
  //  { label: 'Action and Adventure', value: 'action_and_adventure' },
    { label: 'Activity Books', value: 'Activity Books' },
    { label: 'Art and Music Books', value: 'Art and Music Books' },
    { label: 'Biographies and Memoirs', value: 'Biographies and Memoirs' },
    { label: "Children's Books", value: "Children's Books" },
    { label: 'Classics', value: 'Classics' },
    { label: 'Comic Book or Graphic Novel', value: 'Comic Book or Graphic Novel' },
    { label: 'Cookbooks', value: 'cookbooks' },
  //  { label: 'Detective and Mystery', value: 'detective_and_mystery' },
    { label: 'Educational Magazines', value: 'Educational Magazines' },
    { label: 'Educational Novels', value: 'Educational Novels' },
    { label: 'Essays', value: 'Essays' },
  //  { label: 'Fantasy', value: 'fantasy' },
    { label: 'Historical Fiction', value: 'Historical Fiction' },
    { label: 'History Books', value: 'History Books' },
  //  { label: 'Horror', value: 'horror' },
    { label: 'Language Learning Books', value: 'Language Learning Books' },
    { label: 'Literary Fiction', value: 'Literary Fiction' },
   // { label: 'Memoirs', value: 'memoirs' },
    { label: 'Poetry', value: 'Poetry' },
    { label: 'Reference Books', value: 'Reference Books' },
    //{ label: 'Romance', value: 'romance' },
    { label: 'School Textbooks', value: 'School Textbooks' },
    { label: 'Science Books', value: 'Science Books' },
    { label: 'Science Fiction (Sci-Fi)', value: 'Sci-Fi' },
    { label: 'Self-Help and Personal Development', value: 'Personal Development' },
    { label: 'Short Stories', value: 'Short Stories' },
    { label: 'Spirituality', value: 'Spirituality' },
    { label: 'Study Guides', value: 'Study Guides' },
   // { label: 'Thrillers and Suspense', value: 'thrillers_and_suspense' },
    //{ label: 'True Crime', value: 'true_crime' },
    { label: 'Workbooks', value: 'Workbooks' },
    { label: 'Others', value: 'Others' },
    
  ];

  export const BOOKGRADES = [
    { label: '1st Grade', value: 'G1' },
    { label: '2nd Grade', value: 'G2' },
    { label: '3rd Grade', value: 'G3' },
    { label: '4th Grade', value: 'G4' },
    { label: '5th Grade', value: 'G5' },
    { label: '6th Grade', value: 'G6' },
    { label: '7th Grade', value: 'G7' },
    { label: '8th Grade', value: 'G8' },
    { label: '9th Grade', value: 'G9' },
    { label: '10th Grade', value: 'G10' },
    { label: '11th Grade', value: 'G11' },
    { label: '12th Grade', value: 'G12' },
    { label: 'College', value: 'College' },
    { label: 'Young Kids', value: 'Yound-Kids' },
    { label: 'Teens', value: 'Teens' },
    { label: 'High School', value: 'High School' },
    { label: 'Middle School', value: 'Middle School' },
  ]